version: "3.8"
name: bazario-docker-compose

services:
  bazario-web:
    image: bazario.web
    container_name: bazario.web
    build:
      context: ../Bazario.Web
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"

  bazario-identity-webapi:
    image: bazario.identity.webapi
    container_name: bazario.identity.webapi
    build:
      context: ..
      dockerfile: ./Bazario.Identity/src/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002"
    command: /wait-for-it.sh bazario.identity.postgres:5432 -- dotnet Bazario.Identity.WebAPI.dll
    depends_on:
      - bazario-identity-postgres

  bazario-identity-postgres:
    image: postgres:latest
    container_name: bazario.identity.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bazario_identity
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/postgres/identity/data/:/var/lib/postgresql/data
      - ./.containers/postgres/identity/log/:/var/log/postgresql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - ./.containers/rabbitmq/queue/data/:/var/lib/rabbitmq
      - ./.containers/rabbitmq/queue/log/:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
