services:
  bazario-identity-webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=5002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@ssw0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

      - DbSettings__ConnectionString=${DB_CONNECTION_STRING}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__ExpirationTimeInMinutes=${JWT_EXPIRATION_TIME_IN_MINUTES}
      - JwtSettings__SecurityAlgorithm=${JWT_SECURITY_ALGORITHM}
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ../Bazario.Identity/src/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
